# Generated by Django 3.0.7 on 2020-08-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20200809_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administrateur',
        ),
    ]
