# Generated by Django 3.0.7 on 2020-08-31 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0006_auto_20200815_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='R',
            field=models.BooleanField(default=False, verbose_name='reserve'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrived',
            field=models.BooleanField(default=False, verbose_name='arrive'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='scan_entre',
            field=models.BooleanField(default=False, verbose_name='scanEntre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='scan_out',
            field=models.BooleanField(default=False, verbose_name='scanSortie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
