# Generated by Django 3.0.7 on 2020-08-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('Inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='entreprise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscriptions',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.smartParking'),
        ),
    ]
