# Generated by Django 3.1.7 on 2022-03-13 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0007_auto_20200831_1651'),
        ('Inscription', '0002_auto_20200808_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscriptions',
            new_name='Profil',
        ),
    ]
