# Generated by Django 3.0.7 on 2020-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('conditions', models.BooleanField(default=True)),
                ('entreprise', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=250)),
            ],
        ),
    ]
