# Generated by Django 3.0.7 on 2020-08-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_profil',
            old_name='adress',
            new_name='adress_entreprise',
        ),
    ]
