# Generated by Django 3.0.7 on 2020-08-02 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_auth', '0002_auto_20200802_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_profil',
            name='admin_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
